apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-load-definition
type: Opaque
stringData:
  load_definition.json: |-
    {
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "users": [
        {
           "name": "rabbitmq",
           "password": 
           "tags": "administrator",
        }
      ],
      "permissions": [
        {
           "user": "rabbitmq",
           "vhost": "/",
           "configure": ".*",
           "write": ".*",
           "read": ".*"
        }
      ],
      "exchanges": [
        {
          "name": "geoedf-all",
          "vhost": "/",
          "type": "direct",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        }
      ],
      "queues": [
        {
          "name": "geoedf-all",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        }
      ],
      "bindings": [
        {
          "source": "geoedf-all",
          "vhost": "/",
          "destination": "geoedf-all",
          "destination_type": "queue",
          "routing_key": "geoedf",
          "arguments": {}
        }
      ]
    }
